// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnornqgaoiyhjmbaeyfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub3JucWdhb2l5aGptYmFleWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTEzOTMsImV4cCI6MjA3MTY4NzM5M30.Z9QrBpmYeirUXtTBJ1x1Sg-uXYg2uttX8poueGR8uAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});